-- 01_objects.sql
-- Database, schema, base tables, error log, and DQ table

CREATE OR REPLACE DATABASE HEALTHCARE_DB;
CREATE OR REPLACE SCHEMA CLAIMS_DATA;
USE DATABASE HEALTHCARE_DB;
USE SCHEMA CLAIMS_DATA;

-- RAW tables
CREATE OR REPLACE TABLE RAW_PATIENTS (
  PATIENT_ID INT,
  PATIENT_NAME STRING,
  DOB DATE,
  GENDER STRING,
  LAST_UPDATED DATE
);

CREATE OR REPLACE TABLE RAW_CLAIMS (
  CLAIM_ID INT,
  PATIENT_ID INT,
  DIAGNOSIS_CODE STRING,
  TREATMENT_CODE STRING,
  CLAIM_AMOUNT NUMBER,
  CLAIM_STATUS STRING,
  SERVICE_DATE DATE,
  LAST_UPDATED DATE
);

-- Curated
CREATE OR REPLACE TABLE DIM_PATIENT (
  PATIENT_SK NUMBER AUTOINCREMENT,
  PATIENT_ID INT,
  PATIENT_NAME STRING,
  DOB DATE,
  GENDER STRING,
  EFFECTIVE_FROM TIMESTAMP_NTZ,
  EFFECTIVE_TO TIMESTAMP_NTZ,
  IS_CURRENT BOOLEAN
);

CREATE OR REPLACE TABLE FACT_CLAIMS (
  CLAIM_ID INT,
  PATIENT_SK INT,
  DIAGNOSIS_CODE STRING,
  TREATMENT_CODE STRING,
  CLAIM_AMOUNT NUMBER,
  CLAIM_STATUS STRING,
  SERVICE_DATE DATE,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Monitoring
CREATE OR REPLACE TABLE ERROR_LOG (
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONTEXT STRING,
  FILE_NAME STRING,
  ROW_NUMBER NUMBER,
  RAW_RECORD STRING,
  ERROR_MESSAGE STRING
);

CREATE OR REPLACE TABLE DQ_RESULTS (
  CHECK_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CHECK_NAME STRING,
  CHECK_RESULT STRING,
  AFFECTED_COUNT NUMBER
);
