-- 02_stage_and_pipe.sql
USE DATABASE HEALTHCARE_DB;
USE SCHEMA CLAIMS_DATA;

-- Replace placeholders with your real integration and bucket
CREATE OR REPLACE FILE FORMAT CSV_STD
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  SKIP_HEADER=1;

CREATE OR REPLACE STAGE HLTH_S3_STAGE
  URL='s3://health-claims-bucket/'
  STORAGE_INTEGRATION = MY_S3_INTEGRATION
  FILE_FORMAT = CSV_STD;

-- Pipes for auto-ingest
CREATE OR REPLACE PIPE PIPE_RAW_PATIENTS AUTO_INGEST = TRUE AS
COPY INTO RAW_PATIENTS
FROM @HLTH_S3_STAGE/patients/
FILE_FORMAT = (FORMAT_NAME => CSV_STD)
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE PIPE_RAW_CLAIMS AUTO_INGEST = TRUE AS
COPY INTO RAW_CLAIMS
FROM @HLTH_S3_STAGE/claims/
FILE_FORMAT = (FORMAT_NAME => CSV_STD)
ON_ERROR = CONTINUE;
