-- 03_dim_patient_scd2.sql
USE DATABASE HEALTHCARE_DB;
USE SCHEMA CLAIMS_DATA;

CREATE OR REPLACE STREAM STRM_PATIENTS ON TABLE RAW_PATIENTS;

-- Task to maintain SCD2
CREATE OR REPLACE TASK TSK_DIM_PATIENT_SCD2
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 5 * * * * UTC'
AS
-- 1) Close existing current rows where a change is detected
MERGE INTO DIM_PATIENT d
USING (
  SELECT DISTINCT PATIENT_ID, PATIENT_NAME, DOB, GENDER
  FROM STRM_PATIENTS
) s
ON d.PATIENT_ID = s.PATIENT_ID
AND d.IS_CURRENT = TRUE
AND (
     NVL(d.PATIENT_NAME,'') != NVL(s.PATIENT_NAME,'')
  OR NVL(d.DOB,'1900-01-01') != NVL(s.DOB,'1900-01-01')
  OR NVL(d.GENDER,'') != NVL(s.GENDER,'')
)
WHEN MATCHED THEN UPDATE SET
  d.EFFECTIVE_TO = CURRENT_TIMESTAMP(),
  d.IS_CURRENT = FALSE;

-- 2) Insert new current rows for new/changed patients
INSERT INTO DIM_PATIENT (PATIENT_ID, PATIENT_NAME, DOB, GENDER, EFFECTIVE_FROM, EFFECTIVE_TO, IS_CURRENT)
SELECT
  p.PATIENT_ID, p.PATIENT_NAME, p.DOB, p.GENDER,
  CURRENT_TIMESTAMP(), NULL, TRUE
FROM (
  SELECT DISTINCT PATIENT_ID, PATIENT_NAME, DOB, GENDER
  FROM STRM_PATIENTS
) p
LEFT JOIN DIM_PATIENT d
  ON d.PATIENT_ID = p.PATIENT_ID AND d.IS_CURRENT = TRUE
WHERE d.PATIENT_ID IS NULL
   OR NVL(d.PATIENT_NAME,'') != NVL(p.PATIENT_NAME,'')
   OR NVL(d.DOB,'1900-01-01') != NVL(p.DOB,'1900-01-01')
   OR NVL(d.GENDER,'') != NVL(p.GENDER,'');
