-- 04_fact_claims_merge.sql
USE DATABASE HEALTHCARE_DB;
USE SCHEMA CLAIMS_DATA;

CREATE OR REPLACE STREAM STRM_CLAIMS ON TABLE RAW_CLAIMS;

CREATE OR REPLACE VIEW V_PATIENT_CURRENT AS
SELECT PATIENT_ID, PATIENT_SK
FROM DIM_PATIENT
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE TASK TSK_FACT_CLAIMS
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 10 * * * * UTC'
AS
MERGE INTO FACT_CLAIMS f
USING (
  SELECT
    c.CLAIM_ID,
    p.PATIENT_SK,
    c.DIAGNOSIS_CODE,
    c.TREATMENT_CODE,
    c.CLAIM_AMOUNT,
    c.CLAIM_STATUS,
    c.SERVICE_DATE
  FROM STRM_CLAIMS c
  LEFT JOIN V_PATIENT_CURRENT p
    ON p.PATIENT_ID = c.PATIENT_ID
) s
ON f.CLAIM_ID = s.CLAIM_ID
WHEN MATCHED THEN UPDATE SET
  f.PATIENT_SK = s.PATIENT_SK,
  f.DIAGNOSIS_CODE = s.DIAGNOSIS_CODE,
  f.TREATMENT_CODE = s.TREATMENT_CODE,
  f.CLAIM_AMOUNT = s.CLAIM_AMOUNT,
  f.CLAIM_STATUS = s.CLAIM_STATUS,
  f.SERVICE_DATE = s.SERVICE_DATE
WHEN NOT MATCHED THEN INSERT (
  CLAIM_ID, PATIENT_SK, DIAGNOSIS_CODE, TREATMENT_CODE, CLAIM_AMOUNT, CLAIM_STATUS, SERVICE_DATE
) VALUES (
  s.CLAIM_ID, s.PATIENT_SK, s.DIAGNOSIS_CODE, s.TREATMENT_CODE, s.CLAIM_AMOUNT, s.CLAIM_STATUS, s.SERVICE_DATE
);
