-- 06_validation_and_monitoring.sql
USE DATABASE HEALTHCARE_DB;
USE SCHEMA CLAIMS_DATA;

-- Null patient surrogate check
INSERT INTO DQ_RESULTS (CHECK_NAME, CHECK_RESULT, AFFECTED_COUNT)
SELECT 'FACT_NULL_PATIENT_SK',
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       COUNT(*)
FROM FACT_CLAIMS
WHERE PATIENT_SK IS NULL;

-- Negative amount check
INSERT INTO DQ_RESULTS (CHECK_NAME, CHECK_RESULT, AFFECTED_COUNT)
SELECT 'FACT_NEGATIVE_AMOUNT',
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       COUNT(*)
FROM FACT_CLAIMS
WHERE CLAIM_AMOUNT < 0;

-- Status whitelist
INSERT INTO DQ_RESULTS (CHECK_NAME, CHECK_RESULT, AFFECTED_COUNT)
SELECT 'FACT_STATUS_WHITELIST',
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       COUNT(*)
FROM FACT_CLAIMS
WHERE CLAIM_STATUS NOT IN ('Approved','Pending','Rejected');
